on: [push]

name: forge test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Change directory
        run: cd contracts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Forge Install
        run: forge install

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot
